//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wprestaurantapp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wprestaurantapp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading restaurant data file. Information shown might be incomplete..
        /// </summary>
        public static string ErrorRestaurantData {
            get {
                return ResourceManager.GetString("ErrorRestaurantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table for.
        /// </summary>
        public static string HeaderTableFor {
            get {
                return ResourceManager.GetString("HeaderTableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string HeaderTelephone {
            get {
                return ResourceManager.GetString("HeaderTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string HeaderTime {
            get {
                return ResourceManager.GetString("HeaderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view map.
        /// </summary>
        public static string LocationMap {
            get {
                return ResourceManager.GetString("LocationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string LocationPhone {
            get {
                return ResourceManager.GetString("LocationPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web.
        /// </summary>
        public static string LocationWeb {
            get {
                return ResourceManager.GetString("LocationWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0} people.
        /// </summary>
        public static string ReservationForMultiple {
            get {
                return ResourceManager.GetString("ReservationForMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for 1 person.
        /// </summary>
        public static string ReservationForSingle {
            get {
                return ResourceManager.GetString("ReservationForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new reservation.
        /// </summary>
        public static string ReservationsNew {
            get {
                return ResourceManager.GetString("ReservationsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à la carte.
        /// </summary>
        public static string TitleAlacarte {
            get {
                return ResourceManager.GetString("TitleAlacarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string TitleLocation {
            get {
                return ResourceManager.GetString("TitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reservation.
        /// </summary>
        public static string TitleReservation {
            get {
                return ResourceManager.GetString("TitleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reservations.
        /// </summary>
        public static string TitleReservations {
            get {
                return ResourceManager.GetString("TitleReservations", resourceCulture);
            }
        }
    }
}
